-- AlterTable
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "schedule" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "budget" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "evaluation" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "kpis" TEXT;
